#!/bin/sh
# dt - dump text from a hierarchical sequence, takes name of tree to dump
# quoted.awk read a schema file and extract the quoted field
# A quoted field is enclosed in double-quote chars "..."
# A quted field may conatin commas but not newlines
# A quoted field may contain double-quote characters", represented by "".
# A quoted field may be empty

argmatch=$1
shift
awk '
BEGIN {
    FS = "," }
$1 == 0 { 
    if ($3 ~ /'$argmatch'/)
	ok = 1
    else
	ok = 0
}

$1 == 1 && ok == 1 {  # this line contains a quoted field
    line = $0
    if (match(line, /".*"/)) {
	 line = substr(line, RSTART + 1, RLENGTH - 2) # removed quotes
	 gsub(/""/, "\"", line)
	 gsub("\f", "\n", line)
	 printf("%s", line)
    }
}' $*

